version: "3.9"

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synquerra_backend_worker
    command: >
      uvicorn main:app --host 0.0.0.0 --port 9001 --reload --timeout-keep-alive 10000 --header server:openforge
    env_file:
      - .env
    volumes:
      - ./:/opt
    ports:
      - "9001:9001"
    environment:
      MQTT_BROKER: ${MQTT_BROKER:-mqtt}
      MQTT_PORT: ${MQTT_PORT:-1883}
      MONGO_URI: ${MONGO_URI:-mongodb://host.docker.internal:27017}
      MONGO_DB: ${MONGO_DB:-synquerra_db}
      IMEIS: ${IMEIS:-}
    # depends_on:
    #   - mqtt
    restart: unless-stopped

  # mqtt:
  #   image: eclipse-mosquitto:2
  #   container_name: synquerra_worker_mqtt
  #   ports:
  #     - "1883:1883"
  #   restart: unless-stopped
